OPENAI_API_KEY="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"
COHERE_API_KEY="u3qpmen61LicdVymPB9ExCmK3aEa6T8MLYQwmjfz"
